### ISSUE TITLE
Add support for videojs 5.8.6

### ISSUE THREAD

**Issue by paladox** [hartman/videojs-ogvjs#10]
Hi updating videojs to 5.8.6 in TimedMediaHanlder, and pulling this patch https://gerrit.wikimedia.org/r/#/c/260963/ and testing it is resulting in js errors

Like TypeError: Unable to get property 'basePath' of undefined or null reference TypeError: Unable to get property 'basePath' of undefined or null reference

Also updating videojs here in the example files results in error SCRIPT5007: Object expected

```
  var player = videojs('videojs-ogvjs-player', {
    techOrder: [ 'ogvjs' ],
    ogvjs: { base: '/ogv.js' }
  } );
```

This plugin worked in Videojs 5.2 or 5.3 but broke somewhere in the videojs releases.

Please fix it.

**Comment by hartman** [comment]
> i thought that was the reason for failing in timedmediahandler but it was not. I fixed the problem it was my mistake when i rebased.
