### ISSUE TITLE
Fullscreen uses WebKit prefix

### ISSUE THREAD

**Issue by bvibber** [hartman/videojs-ogvjs#11]
Should avoid hardcoding that for IE/edge

**Comment by hartman** [comment]
Shouldn't be a problem, it is only the fallback situation, for older HTML5 and possibly iOS and Android really. I could probably just remove it. The actual fullscreen is:
https://github.com/videojs/video.js/blob/0b26d83e9981560f641f70feb270d6ddcc49ec41/src/js/fullscreen-api.js

And used here.
https://github.com/videojs/video.js/blob/fa27cc7dbf601239999b0f99ca18318623da863f/src/js/player.js

**Comment by hartman** [comment]
removed this, no need to support old style prefixed fullscreen as far as i'm concerned.
