### ISSUE TITLE
Pull ogv.js dist via package manager?

### ISSUE THREAD

**Issue by bvibber** [hartman/videojs-ogvjs#12]
Would it be desirable to pull ogv.js via npm or bower as a dep instead of copying the dist files? I'm going to set these up for 1.1 dist soon

**Comment by hartman** [comment]
Yes it would be, the only reason i have it hardcopied in now, is because it wasn't in npm yet (i prefer npm personally).

**Comment by bvibber** [comment]
Great, I'll have that set up for the 1.1 update.
