### ISSUE TITLE
Issue when selecting higher or lower resolutions

### ISSUE THREAD

**Issue by paladox** [hartman/videojs-ogvjs#7]
Hi this works but selecting a differen resolution dosent. It shows them and allows you to click them but dosent apply the resolution if clicked.

Please fix that.

I doint know if that is because of the player or this.

**Comment by paladox** [comment]
Tested it is with this plugin.

**Comment by hartman** [comment]
This seems to be because of how ogv.js is implemented. It doesn't detect changes to the src property. This probably works by change in the old player, because the old player simply disposes the entire playback context and starts from scratch.

**Comment by paladox** [comment]
Oh, thanks for working on this.

**Comment by paladox** [comment]
No longer a issue was fixed in videojs 5.10.1, ive tested and changing resolution works.

Looks like https://github.com/videojs/video.js/pull/3285 this is the fix.

Ive submitted the pull request here https://github.com/hartman/videojs-ogvjs/pull/18

Ive also updated it here https://gerrit.wikimedia.org/r/#/c/284375/

**Comment by hartman** [comment]
No it was fixed because of changes in ogv.js 1.1.0 alpha (and one small change in videojs-ogv.js 1.1.0). Though the videojs was an annoying bug, it did not prevent the actual switching.

If you experience this, then it just means that you had newer versions of those libraries installed (possibly without realizing).

**Comment by paladox** [comment]
@hartman Hi I didn't use ogv.js 1.1.0 I used this patch https://gerrit.wikimedia.org/r/#/c/284375/ which still uses the old ogv.js 1.0 version. Using it fixed it since there was a fix in videojs that fixed changing sources.

**Comment by paladox** [comment]
Thanks.
